### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [fabiendelpierre/my-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

Thanks!

**Comment by fabiendelpierre** [comment]
Hi there,

I'm surprised you found this at all as it's just intended for myself to store my zsh theme for my own dotfiles, but I guess you've got something scraping GitHub for this sort of thing 😄

Anyway, I don't mind sharing at all, I'll set up the license and screenshot in the coming days and ping you again when it's done.

**Comment by unixorn** [comment]
Thanks!

**Comment by fabiendelpierre** [comment]
@unixorn all set, thanks for reaching out!
